### ISSUE TITLE
Error accessing course records file

### ISSUE THREAD

**Issue by averywallis** [WardBenjamin/CanvasCourseDownloader#1]
First off, great tool that I'll definitely be using once it doesn't break for me. 

It runs to the point of trying to open the records/{course_safe}.txt as course_log, but then can't find that file for what was my calc III course like 4 years ago. Here's the error/info it threw for me (in code and image format):

`` RESTART: D:\Downloads\CanvasCourseDownloader-master\CanvasCourseDownloader-master\main.py
Traceback (most recent call last):
  File "D:\Downloads\CanvasCourseDownloader-master\CanvasCourseDownloader-master\main.py", line 77, in <module>
    with open(f"records/{course_safe}.txt", "w", encoding="utf-8") as course_log:
FileNotFoundError: [Errno 2] No such file or directory: 'records/5123_a17_-_calculus_iii.txt' ``

![image](https://user-images.githubusercontent.com/16786962/115646432-1e5a0980-a2f0-11eb-94a1-ab28b74c70b4.png)

**Comment by averywallis** [comment]
Probably should have mentioned, running in Python 3.9.4 on a Windows 10 machine

**Comment by WardBenjamin** [comment]
I haven not been able to replicate with my own setup - are you sure that the `records/` folder exists and permission are set correctly (you can write to it)?

**Comment by averywallis** [comment]
Older version is still broken (directory is definitely writable and records folder exists). Tried with the newest (0.2 I think) version, which got farther and actually downloaded some materials for the first class before running into some new error. Once again, here's the error stuff. Sounds like it's unable to access some assignment details cause they don't exist. Seems like it's from a class where the prof has disabled the viewing of some of the materials. Also, none of the generated PDF files for the homework's are openable, they all fail to be read as they're corrupted or not actually pdfs. All the generated HTML files are valid though.


`Assignment submission has no submission type??
Found assignment with unknown submission type None; can't download
Assignment submission has no submission type??
Found assignment with unknown submission type None; can't download
<src.filesystem.FileSystem object at 0x000001C7E4AB81C0>
Trying to download {'class': ['instructure_file_link', 'instructure_scribd_file'], 'title': 'HW1.pdf', 'href': 'https://canvas.wpi.edu/courses/5123/files/671843/download?wrap=1', 'data-api-endpoint': 'https://canvas.wpi.edu/api/v1/courses/5123/files/671843', 'data-api-returntype': 'File'} as a Canvas file
Trying to download {'class': ['instructure_file_link', 'instructure_scribd_file'], 'title': 'HW2.pdf', 'href': 'https://canvas.wpi.edu/courses/5123/files/687031/download?wrap=1', 'data-api-endpoint': 'https://canvas.wpi.edu/api/v1/courses/5123/files/687031', 'data-api-returntype': 'File'} as a Canvas file
Trying to download {'class': ['instructure_file_link', 'instructure_scribd_file'], 'title': 'HW3.pdf', 'href': 'https://canvas.wpi.edu/courses/5123/files/702966/download?wrap=1', 'data-api-endpoint': 'https://canvas.wpi.edu/api/v1/courses/5123/files/702966', 'data-api-returntype': 'File'} as a Canvas file
Traceback (most recent call last):
  File "D:\Downloads\CanvasCourseDownloader-master (1)\CanvasCourseDownloader-master\course.py", line 72, in <module>
    c.download()
  File "D:\Downloads\CanvasCourseDownloader-master (1)\CanvasCourseDownloader-master\course.py", line 44, in download
    assignment.download(dir_name + "/assignments")
  File "D:\Downloads\CanvasCourseDownloader-master (1)\CanvasCourseDownloader-master\src\assignment.py", line 88, in download
    linkfile.download(path)
  File "D:\AveryW\Assorted Programs\Python3-9-4\lib\site-packages\canvasapi\file.py", line 30, in download
    response = self._requester.request("GET", _url=self.url)
  File "D:\AveryW\Assorted Programs\Python3-9-4\lib\site-packages\canvasapi\requester.py", line 246, in request
    raise ResourceDoesNotExist("Not Found")
canvasapi.exceptions.ResourceDoesNotExist: Not Found`

![image](https://user-images.githubusercontent.com/16786962/116914585-e8ceed80-ac18-11eb-86ab-bcc74ee08ecd.png)
